plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Metrics/BlockLength:
  Exclude:
    - 'db/**/*.rb'

Style/Documentation:
  Exclude:
    - 'app/**/application_*.rb'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'test/**/*.rb'
